### ISSUE TITLE
update module dependency version of preshed

### ISSUE THREAD

**Issue by DeanHe** [explosion/thinc#15]
Hi,

I try to install this module by wheel, it requires preshed module <0.47, but the current preshed module is 1.0.0

**Comment by honnibal** [comment]
I'm not sure I understand. Isn't there a preshed wheel 0.46?

I bumped the preshed version to 1.0, but I don't currently have resources to build wheels.

**Comment by DeanHe** [comment]
yes, there is a [preshed wheel 0.46.3](https://pypi.python.org/pypi/preshed/0.46.3), but it also depends on cymem (<1.31.0,>=1.30), which is out of date, and can't find a matching cymem wheel.

**Comment by pavancs** [comment]
I am facing similar issue on a 32bit windows machine. I am able to install preshed 1.0, but not preshed 0.46. Hence, not able to install thinc.

**Comment by honnibal** [comment]
I think the versions are actually incompatible. Because these are almost entirely C extensions (in Cython), many code changes will make wheels incompatible with each other. For instance, preshed 1.0.0 adds some extra attributes, breaking binary compatibility.

Have you tried Conda? It might have some more up to date wheels. Otherwise...Unfortunately, 32bit Windows is a difficult platform to fully support :(.
