### ISSUE TITLE
Configuration: interpolation of resolved values

### ISSUE THREAD

**Issue by hbredin** [explosion/thinc#352]
I have a use case where I need to interpolate resolved values in a `thinc.config` configuration file:

```ini
[task]
@task = "MyTask"

[architecture]
task = ${task}   <-- interpolated here...

[training]
task = ${task}  <-- ... and also here
```

`Config.from_disk("config.cfg")` gives me the following error:

```python
InterpolationDepthError: Recursion limit exceeded in value substitution: option 'task' in section 'architecture' contains an interpolation key which cannot be substituted in 10 steps. Raw value: '${task}'
```

This is not a suprise: this limitation is described in the documentation.

> Interpolation happens when the config is parsed, i.e. when you create a Config object from a file, string, etc. and before registered functions are resolved. This means that you can only use it for hard-coded values like numbers and strings, not to define placeholders for resolved values. For instance, the [model] section in this example will be resolved to an instance of Relu – but you wouldn’t be able to use ${model} as the argument to another function defined in the config. 

However, the documentation also says
> To achieve this, you can either define another nested block or variable positional arguments.

I am not sure what this means exactly. How would one achieve what I am trying to achieve with `positional arguments` or `nested block` in my particular case?

**Comment by ines** [comment]
Hey, nice to see you on the Thinc tracker! 👋

I just had to re-read that paragraph (that I likely wrote myself) a couple of times to refresh my memory, so it's definitely more confusing than it should have been and we should adjust this. 

I'm pretty sure what it means is that you can rewrite your config to look like this:

```ini
[architecture]

[architecture.task]
@task = "MyTask"

[training]

[training.task]
@task = "MyTask"
```

If `MyTask` has arguments, you could make those variables, so you're only defining them once. However, it's of course not fully equivalent, because here you'd be creating _two separate instances_ of the task and you're not passing the same instance into both.

I don't think there's currently a way to use the function registry to create an object once and then pass that same instance into multiple other functions. At least I can't think of one and couldn't make it work so far? Maybe @honnibal has an idea.

**Comment by honnibal** [comment]
Agree that something like this should be possible, and isn't currently.

In the original design I figured something like this would be possible, likely with nicer syntax:

```
[task]
name = "hi"
data = null

[task.data]
@task = "MyTask"

[obj1]
arg = ${task:data}

[obj2]
arg = ${task:data}
```

This works because the Python configparser actually doesn't do early substitution of the references. It keeps them as pointers, so when we replace `task.data` using the section flattening, the references will resolve to the new value.

However, as we've added more validation, even this ugly workaround no longer functions: we check that `task.data` isn't a previously set value, and we raise on the conflict (correctly).

So in summary, there are two problems to solve before we can make this feature work.

1) `${task}` refers to a block, not a value-within-a-block. That's not legal with the current interpolation, but IMO we do want it to be legal.

2a) `[task.block]` will be filled to `cfg["task"]["block"]` after `${task:block}` checks that the value exists. We'll currently get an exception from that, because it's a reference to a missing value. We don't want to force the user to specify a dummy value.

2b) If we do solve 2a by forcing the user to specify a dummy value, we'll have to solve the different problem of config validation and making sure the block gets assigned to overwrite the dummy value. But this is all bad, I'm sure we don't want this path.

I think we can solve this in one of two ways:

1) Initially, we could set `interpolation=False`. This will give us a chance to get in and fix the data while it's still just a dict. We can then activate the interpolation using the built-in `ExtendedInterpolation` class.
2) We can implement our own interpolation handler, which does things our way.

I think 2) seems better? It sets us up for more changes in future, and is less weird and hacky.

**Comment by honnibal** [comment]
Here's the class we need to subclass: https://github.com/python/cpython/blob/master/Lib/configparser.py#L448 . It needs to be passed into our `get_configparser` function.

We need to implement four hooks. I wouldn't inherit, I think that just makes it less clear.

```
class ConfigInterpolation:
    def before_get(self, parser: ConfigParser, section: str, option: str, value: str, defaults: dict):
        return value

    def before_set(self, parser: ConfigParser, section: str, option: str, value: str):
        return value

    def before_read(self, parser: ConfigParser, section: str, option: str, value: st:r):
        return value

    def before_write(self, parser: ConfigParser, section: str, option: str, value: str):
        return value
```

If we want to use the private method of the existing `ExtendedInterpolation` class, I'd rather we vendored it in. It's kind of ugly to be calling into private methods of the standard library.

**Comment by hbredin** [comment]
Thanks for looking into this so quickly.

I went with a workaround for now (i.e. set the "task" attribute manually instead of relying on `Config.from_disk`) but this new feature would definitely make my code less ugly.
