### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by Freddex** [explosion/thinc#396]
Yesterday, I first came across thinc and checked out the docs (https://thinc.ai/docs). I distinctly remember some cool code samples on how to embed TensorFlow and PyTorch, which is precisely my use case (making a custom NER model for SpaCy, wrapping it with thinc, and plugging it into SpaCy). Today, the website changed, and the code samples are gone. Were those out of date? 

Sorry if this issue is a bit vague, I didn't know where else to raise this. Hope that's okay. :)

**Comment by honnibal** [comment]
Hey,

This is a bug with the site, thanks for pointing it out! We're just migrating it so that the docs are hosted within the repo, because we're gearing up to release the spaCy v3 nightly. That's the version of spaCy that will use Thinc, making it easy to do what you're after. Don't publicise this, but you can find a sneak peek here: https://nightly.spacy.io

It's all a bit bleeding edge though. You'll be better off waiting a couple of days until we go live, but you can already start looking around if you want.

Currently the PyTorch wrapping works really well, the Tensorflow wrapping is not so great. We've been disappointed with how long it's taken Tensorflow to adopt the DLPack standard, which allows array interchange with the library. Without DLPack, we're stuck copying data to Tensorflow via the CPU, which is super inefficient. I understand DLPack support is now in the experimental branch so hopefully it's out soon 🤞

**Comment by honnibal** [comment]
Okay, should be fixed now :)
