### ISSUE TITLE
How to enable fp16 when training transformer model using spacy-transformer

### ISSUE THREAD

**Issue by brightgems** [explosion/thinc#497]
try to train transformer model in spacy with fp16 enabled. alrough apex is installed, fp16 does not work at any time.

is there any way to turn on this paramenter?

**Comment by adrianeboyd** [comment]
Hi, there's a new experimental `mixed_precision` option in the transformer architecture for `spacy-transformers` v1.1: https://spacy.io/api/architectures#TransformerModel

I don't think this setting has much direct interaction with `thinc`, so I'll close this issue here. Please open a new issue in the spacy repo if you run into problems with this.
