### ISSUE TITLE
numpy.ndarray size changed   Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by hzg456** [explosion/thinc#515]
error showed in terminal:  
File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

numpy with version 1.19.0 is installed in my server
Could you please show me how to solve this problem ?
thx!

**Comment by adrianeboyd** [comment]
How have you installed thinc? Are you compiling from source?

**Comment by hzg456** [comment]
I installed thinc using "pip" ,I installed  thinc v8.0.3

**Comment by adrianeboyd** [comment]
Depending on your environment and the options you give, pip can install a binary wheel or from source.

Probably what happened is that you installed thinc from source, which uses the most recent version of numpy when it's compiling thinc, but the version of numpy is your venv is lower (1.21.0 vs 1.19.0).

If you're not installing from source on purpose, typically you need to upgrade pip (`pip install -U pip setuptools wheel`) before installing so that pip can identify the right binary wheel, which should be available for all common OSes/python versions for x86_64 (just not other architectures like arm64).

If you're compiling from source on purpose, one option is to use the same build constraints that we do for binary wheels on pypi, so that it uses an earlier version of numpy while compiling, which prevents these kinds of errors:

```bash
PIP_CONSTRAINT=https://raw.githubusercontent.com/explosion/thinc/master/build-constraints.txt pip install thinc
```

**Comment by hzg456** [comment]
I upgraded pip` (pip install -U pip setuptools wheel)`, and then installed thinc v8.0.3 again using pip. However, the error still existed:
 ```
 File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
  File "thinc/backends/linalg.pyx", line 2, in init thinc.backends.linalg
  File "blis/py.pyx", line 1, in init blis.py
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by adrianeboyd** [comment]
That's the same thing also happening with the library `blis`. Try doing the same thing for `blis`. To be on the safe side, also add `--no-cache-dir` to make sure it's using the version from pypi and not from a local cache:

```bash
pip install -U pip setuptools wheel
pip uninstall -y blis thinc
pip install blis thinc --no-cache-dir
```

**Comment by zhongpeixiang** [comment]
This error happened to me as well

**Comment by Divyosmi** [comment]
Please use the command
```{bash}
pip install "thinc==8.0.0rc6.dev0"
```

**Comment by Divyosmi** [comment]
The issue has resolved on my side. Please revert back if you have any problems yet and please revert back to the pull requests. Thank you.

**Comment by zhongpeixiang** [comment]
Why the requirement.txt says numpy>=1.15.0 but it actually cannot run on numpy 1.18.1.

**Comment by zhongpeixiang** [comment]
THIS IS VERY FRUSTRATING

**Comment by zhongpeixiang** [comment]
An alternative solution: https://github.com/explosion/spaCy/issues/6949

**Comment by adrianeboyd** [comment]
@Divyosmi : Using an out-dated release candidate `.dev` release isn't a good alternative, please open a new issue if you're running to problems.

**Comment by adrianeboyd** [comment]
I think this particular issue is resolved. Please open a new issue if you're running into problems.
