### ISSUE TITLE
security vulnerability CVE-2021-29510 is fixed in pydantic 1.9.0

### ISSUE THREAD

**Issue by Moisan** [explosion/thinc#622]
pydantic security vulnerability [CVE-2021-29510](https://github.com/samuelcolvin/pydantic/security/advisories/GHSA-5jqp-qgf6-3pvh) is [fixed in pydantic 1.9.0](https://github.com/samuelcolvin/pydantic/commit/7e83fdd2563ffac081db7ecdf1affa65ef38c468)

I propose that we use `<2.0.0` instead of `!=1.9.0` (like [fastapi does](https://github.com/tiangolo/fastapi/blob/eddbae948f04e13fe412dc45a569d10e34b698a4/pyproject.toml#L39)) in the `requirements.txt` file.

**Comment by adrianeboyd** [comment]
This security vulnerability is also fixed in pydantic v1.8.2, so it shouldn't be a concern with the current `thinc` requirements.

We have work in progress on making `thinc` compatible with newer versions of `pydantic` and `mypy` (#599) so we hope we can support newer versions of these libraries soon, but this is separate from concerns about this security vulnerability.
