### ISSUE TITLE
'GLIBC_2.29' not found

### ISSUE THREAD

**Issue by shashank140195** [explosion/thinc#876]
Hi, I am using Python 3.8 and I have Thinc 7.0.2 installed in my environment. I am getting the below error while training using the Allennlp library. 

`ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/sgu260/.local/lib/python3.8/site-packages/thinc/neural/ops.cpython-38-x86_64-linux-gnu.so`

How can I resolve it? I tried updating thinc but the latest versions are not compatible with Spacy 2.1.4.

**Comment by danieldk** [comment]
This error means that Python attempts to load a module that was built on a system with glibc 2.29 on a system with a glibc version that is older than 2.29. Since we don't provide precompiled Python 3.8 wheels of Thinc 7.0.2, did you compile Thinc on a different machine? Maybe that machine uses glibc 2.29?

**Comment by adrianeboyd** [comment]
Please reopen if you're still running into problems.
